---
- name: Fetch file from the server
  fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ./tmp/rke2.yaml
    flat: yes

- name: Modify the file contents
  lineinfile:
    path: ./tmp/rke2.yaml
    regexp: 'server: https://127.0.0.1:6443'
    line: '    server: https://{{ apiserver_endpoint }}:6443'
    state: present
  delegate_to: localhost
  become: false

- name: Save modified file locally
  copy:
    src: ./tmp/rke2.yaml
    dest: kube_config_cluster.yml
    mode: '0644'
  delegate_to: localhost
  become: false
