---
# Download logs of rke2-init.service from the nodes to localhost.
# Note that log_destination must be set.

- name: Fetch rke2-init.service logs
  ansible.builtin.command:
    cmd: journalctl --all --unit=rke2-init.service
  changed_when: false
  register: rke2_init_log

- name: Create {{ log_destination }}
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.file:
    path: "{{ log_destination }}"
    state: directory
    mode: "0755"

- name: Store logs to {{ log_destination }}
  delegate_to: localhost
  become: false
  ansible.builtin.template:
    src: content.j2
    dest: "{{ log_destination }}/rke2-init@{{ ansible_hostname }}.log"
    mode: 0644
  vars:
    content: "{{ rke2_init_log.stdout }}"
