---

- name: Wait for node-token
  wait_for:
    path: "/var/lib/rancher/rke2/server/node-token"

- name: Register node-token file access mode
  stat:
    path: "/var/lib/rancher/rke2/server/node-token"
  register: p

- name: Change file access node-token
  file:
    path: "/var/lib/rancher/rke2/server/node-token"
    mode: "g+rx,o+rx"

- name: Read node-token from master
  slurp:
    path: "/var/lib/rancher/rke2/server/node-token"
  register: node_token

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access
  file:
    path: "/var/lib/rancher/rke2/server/node-token"
    mode: "{{ p.stat.mode }}"
