---

- name: Create rke2.service.d directory
  file:
    path: '{{ systemd_dir }}/rke2-agent.service.d'
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Copy rke2 http_proxy conf file
  template:
    src: "http_proxy.conf.j2"
    dest: "{{ systemd_dir }}/rke2-agent.service.d/http_proxy.conf"
    owner: root
    group: root
    mode: '0755'
