---
- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - rke2
    - rke2-init
    - rke2-server
    - rke2-agent

- name: RUN pkill on the shims
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "rke2/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Umount rke2 filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/rke2
    - /var/lib/kubelet/pods
    - /var/lib/kubelet/plugins
    - /run/netns/cni-
  loop_control:
    loop_var: mounted_fs

- name: Remove service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/rke2
    - "{{ systemd_dir }}/rke2.service"
    - "{{ systemd_dir }}/rke2-init.service"
    - "{{ systemd_dir }}/rke2-server.service"
    - "{{ systemd_dir }}/rke2-agent.service"
    - /etc/rancher/rke2
    - /run/k3s
    - /run/flannel
    - /etc/rancher/
    - /var/lib/kubelet
    - /var/lib/rancher/rke2
    - /var/lib/rancher/
    - /var/lib/cni/

- name: Remove rke2 http_proxy files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ systemd_dir }}/rke2-server.service.d"
    - "{{ systemd_dir }}/rke2-agent.service.d"
  when: proxy_env is defined

- name: Reload daemon_reload
  systemd:
    daemon_reload: yes


- name: Remove tmp directory used for manifests
  file:
    path: /tmp/rke2
    state: absent

- name: Check if rc.local exists
  stat:
    path: /etc/rc.local
  register: rcfile
